# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3318d074e691d58ef18f060a7c3f31ed45ff2faf460750c7595f309da56be3107b8b8143098645e6080dd83ce5d893a2991216fb071b2689fdb62a20abb7b7a6

test:
  secret_key_base: 10bbf4e048ee19fa5dcc9506ed771cb54f3d781db24275171ca23560323420202b77d637793513900d37f68bcb2f8c241b3dbb21396c624ce4da11123d89a4ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
